sudo: false
dist: bionic
language: python
cache: pip

addons:
  apt:
    packages:
    - pandoc

python:
- 3.6
- 3.7
- 3.8
- pypy3

jobs:
  allow_failures:
  - python: pypy3

before_install:
- pip install -U -r ci/requirements.txt

install:
- pip install .

script:
- coverage run -m orthoani -q tests/data/*.FMIY01000001.fna -r tests/data/*.FMIY01000001.fna
- coverage run -m orthoani -q tests/data/*.FMIY01000001.fna -r tests/data/*.FMIY01000002.fna

after_success:
- coverage combine
- coverage xml --include "pronto/*"
- codecov
- python-codacy-coverage -r coverage.xml

before_deploy:
- python setup.py sdist bdist_wheel
- twine check dist/*

deploy:
- provider: script
  script: twine upload --skip-existing dist/*
  skip_cleanup: true
  on:
    python: 3.8
    tags: true
    repo: althonos/orthoani

notifications:
  email:
  - althonosdev@gmail.com
